SELECT CAR_ID, CH.CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM
    (SELECT C.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE IN ('SUV', '세단') 
        AND C.CAR_ID NOT IN 
            (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE END_DATE > '2022-11-01')
    GROUP BY C.CAR_ID) CH
JOIN
    (SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%') P
ON CH.CAR_TYPE = P.CAR_TYPE
WHERE 500000 <= DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100) AND DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100) < 2000000
ORDER BY FEE DESC, CH.CAR_TYPE, CAR_ID DESC