SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' 
        and (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID

# SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME, O.SEX_UPON_OUTCOME
# FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
# ORDER BY I.ANIMAL_ID