# SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO I JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
# WHERE ADDRESS LIKE '%서울%'
# GROUP BY I.REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
JOIN REST_REVIEW AS RR
ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RR.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC;