SELECT CASE
            WHEN SUBSTRING(DIFFERENTIATION_DATE, 6, 2) <= '03' THEN '1Q'
            WHEN SUBSTRING(DIFFERENTIATION_DATE, 6, 2) <= '06' THEN '2Q'
            WHEN SUBSTRING(DIFFERENTIATION_DATE, 6, 2) <= '09' THEN '3Q'
            ELSE '4Q'
        END AS QUARTER,
        COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER