SELECT HISTORY_ID, ROUND(DAILY_FEE * DAY * (1 - IFNULL(DISCOUNT_RATE, 0) / 100)) AS FEE
FROM 
    (SELECT H.history_id, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DAY, 
        (CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C 
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
        ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE ='트럭') A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON A.CAR_TYPE = P.CAR_TYPE AND A.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC