SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY TOTAL_ORDER + J_TOTAL_ORDER DESC
LIMIT 3